### ISSUE TITLE
upgrading to HB1.3.0 produces 'model' error on boot

### ISSUE THREAD

**Issue by woodgieboodgie** [sfeakes/sprinklerd#26]
[23/02/2021, 7:04:56 pm] [homebridge-sprinklerd] This plugin threw an error from the characteristic 'Model': Error: [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory. Ignoring new value.
    at Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1991:38)
    at Characteristic.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1457:21)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Characteristic.handleGetRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:632:24)
    at Characteristic.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2127:22)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27) See https://git.io/JtMGR for more info.

**Comment by woodgieboodgie** [comment]
Hi again Sean,
Any chance you could have a look at this?  Seems any Homebridge version beyond 1.2.5... seeming to suggesting there is no value against 'Model'.  What do you suspect it is?
